suborgrepos:
  - guardians.*

repository:
  auto_init: true
  topics: [operations, guardians]
  private: true
  has_issues: true
  has_projects: false
  has_wiki: true
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_auto_merge: false
  delete_branch_on_merge: true

labels:
  include:
    - name: bugfix
      color: '#CC0000'
      description: A label for a bug.
    - name: feature
      color: "#336699"
      description: A label for a feature.
  exclude:
    - name: ^guest-
    - name: ^crew-

teams:
  - name: backend-guest
    permission: push
  - name: backend-guest-admins
    permission: admin
  - name: guardians
    permission: pull
  - name: guardians-admins
    permission: admin
  - name: service-accounts
    permission: push
  - name: platform
    permission: push

branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users:
            - rccl-github
          teams:
            - backend-guest-managers
            - backend-guest-leads
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions: null

autolinks:
  - key_prefix: "RTB-"
    url_template: "https://jira.rccl.com/browse/RTB-<num>"

validator:
  pattern: "[a-zA-Z0-9_-]+"
