# This settings can be used to create suborg level settings

# List of repos that belong to the suborg
suborgrepos:
  - platform.appdynamics-otel-collectors-k8s
  - platform.appdynamics-otel-k8s
  - platform.portworx-k8s
  - platform.dkp-cluster
  - platform.k8s-cluster-state
  - platform.external-secrets-k8s
  - platform.f5-k8s
  - platform.graphql-cosmo-k8s
  - platform.kommander-k8s
  - platform.terraform-aws-modules
  - platform.terraform-aws-live
  - platform.cert-manager
  - platform.argocd-library
  - platform.confluent-kafka-k8s
  - platform.splunk-k8s
  - platform.harbor-k8s
  - platform.cloudwatch-agent-k8s
  - platform.argocd
  - platform.k8s-deployments
  - platform.quarterly-reboot
  - platform.controlcenter-standalone
  # - platform.kubelogin # exclude
  - platform.konvoy
  - platform.jenkins-k8s
  - platform.iris
  - platform.apigee-user-mgmt
  - platform.f5-automator
  - platform.architecture-diagrams
  - platform.grafana_configurator_role
  - platform.library
  - platform.java_open
  - platform.ansible_galaxy_example
  - platform.velero-k8s
  - platform.minio-automator
  - platform.apigee-automator
  - platform.nexus-k8s
  - platform.sonarqube-k8s
  - platform.dkp-image
  - platform.base-image
  - platform.convert-to-jenkins-job
  - platform.argo-rollouts
  - platform.jenkins-job-archives
  - platform.platform-admission-webhook-k8s
  - platform.vmware-exporter-k8s
  - platform.terraform-github-live
  - platform.terraform
  - platform.sequence-scheduler
  - platform.safe-settings
  - platform.redis-k8s
  - platform.rabbitmq-k8s
  - platform.prometheus-nexus-exporter
  - platform.postgres-operator
  - platform.platform-admission-webhook
  - platform.nginx-proxy
  - platform.nginx-k8s
  - platform.minio-k8s
  - platform.k8s-toolkit
  - platform.groovy-blocks-maven-sample
  - platform.groovy-blocks
  - platform.grafana-automation-dashboards
  - platform.gatekeeper-library
  - platform.etcd-backup
  - platform.contrast
  - platform.consul-k8s
  - platform.ci-pipeline-maven
  - platform.appdynamics-k8s
  - platform.grafana-dashboards
  - platform.selenium-grid-k8s
  - platform.minio-standalone

# You can use Glob patterns

# suborgteams:
#   - platform-leads
#   - platform
#   - platform-collaborators
# These settings are synced to GitHub. by https://github.com/github/safe-settings

repository:
  # This is the settings that need to be applied to all repositories in the org
  # See https://docs.github.com/en/rest/reference/repos#create-an-organization-repository for all available settings for a repository
  # A short description of the repository that will show up on GitHub

  # Keep this as true for most cases
  # A lot of the policies below cannot be implemented on bare repos
  # Pass true to create an initial commit with empty README.
  auto_init: true
  # A list of topics to set on the repository - can alternatively set like this: [github, probot, new-topic, another-topic, topic-12]
  topics:
  # Either `true` to make the repository private, or `false` to make it public.
  # If this value is changed and if Org members cannot change the visibility of repos
  # it would result in an error when updating a repo
  private: true
  # Can be public or private. If your organization is associated with an enterprise account using
  # GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal.
  visibility: private
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true
  # The default branch for this repository.
  default_branch: main
  # Desired language or platform [.gitignore template](https://github.com/github/gitignore)
  # to apply. Use the name of the template without the extension.
  # For example, "Haskell".
  # gitignore_template: node

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true
  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true
  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true
  # Either `true` to allow auto-merge on pull requests,
  # or `false` to disallow auto-merge.
  # Default: `false`
  allow_auto_merge: false
  # Either `true` to allow automatically deleting head branches
  # when pull requests are merged, or `false` to prevent automatic deletion.
  # Default: `false`
  delete_branch_on_merge: true
# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  # Labels: define labels for Issues and Pull Requests
  include:
    - name: bug
      color: CC0000
      description: An issue with the system
    - name: feature
      # If including a `#`, make sure to wrap it with quotes!
      color: "#336699"
      description: New functionality.
    - name: first-timers-only
      # include the old name to rename an existing label
      oldname: Help Wanted
      color: "#326699"
    - name: new-label
      # include the old name to rename an existing label
      oldname: Help Wanted
      color: "#326699"
  exclude:
    # don't delete any labels created on GitHub that starts with "release"
    - name: ^release
milestones:
  # Milestones: define milestones for Issues and Pull Requests
  - title: milestone-title
    description: milestone-description
    # The state of the milestone. Either `open` or `closed`
    state: open
teams:
  - name: platform-leads
    permission: admin
  - name: platform
    permission: push
  - name: service-accounts
    permission: pull
  - name: megatron
    permission: push
branches:
  # If the name of the branch value is specified as `default`, then the app will create a branch protection rule to apply against the default branch in the repo
  - name: default
    # https://docs.github.com/en/rest/reference/branches#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
        require_last_push_approval: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        # Allow specific users, teams, or apps to bypass pull request requirements. Set to null to disable.
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams:
            - platform-leads
        dismissal_restrictions:
          users: []
          teams:
            - platform-leads
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null
# See the docs (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources) for a description of autolinks and replacement values.
autolinks:
  - key_prefix: "SHIP-"
    url_template: "https://jira.rccl.com/browse/SHIP-<num>"
validator:
  #pattern: '[a-zA-Z0-9_-]+_[a-zA-Z0-9_-]+.*'
  pattern: "[a-zA-Z0-9_-]+"
